### ISSUE TITLE
ContentType without slug should not cause notice

### ISSUE THREAD

**Issue by pcsonka** [bolt/configuration-notices#27]
Lets say we have a content type:
```
foo:
    name: foo
    singular_name: bar
    title_format: "{name}"
    fields:
        name:
            type: text
            required: true
        email:
            type: email
            required: true
    viewless: true
```

It does not have a slug, but when content types instantiated in `bolt/core/src/Entity/Content.php::__construct()` Bolt actually adds an empty slug field automatically. The `bobdenotter/configuration-notices/src/Checks.php::slugUsesCheck()` only checks if the content type has any slugs, it wont check if its empty or not.

I am not sure that leaving out the slug is a possible intended way of use for the content types or its just an accidentally working way, butt currently on bolt4 its working, so I don't think the configuration notice should throw an error for this.
